### ISSUE TITLE
Checkbox value is not working is SCSS @if

### ISSUE THREAD

**Issue by alextseitlin** [evoko/zendesk-theme#35]
I found an issue and wanted to know if you can help me.

The goal is to use scss `@if` and "type": “checkbox” together. But the value of "type": “checkbox”  is not recognized in SCSS as true or false. 

I have this setup

```json
{
  "label": "General",
  "variables": [
    {
      "identifier": "_show_animations",
      "type": "checkbox",
      "description": "Enable animations o all pages",
      "label": "Show animations?",
      "value": false
    }
  ]
}
```

and this is scss
```scss
a {
	@if $_show_animations {
		background-color: black;
	}
}
```

I don't understand what value is passed because it does not work. Replacing it with true or false works. Also if I create another variable ($something: true) also works. Like this:

```scss

$something: true;

a {
	@if $something {
		background-color: black;
	}
}
```
